const objectives = [
  {
    cellX: 0,
    cellY: 0,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 24,
    claimedByPlayerId: null,
    objective: {
      displayName: "Find 10 beautiful dogs ",
      id: 24,
      countable: true,
      countLimit: 10,
    },
  },
  {
    cellX: 1,
    cellY: 4,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 11,
    claimedByPlayerId: null,
    objective: {
      displayName: "Visit a dog park",
      id: 11,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 2,
    cellY: 0,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 8,
    claimedByPlayerId: null,
    objective: {
      displayName: "Bike (or walk your bike) through a night market",
      id: 8,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 2,
    cellY: 1,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 18,
    claimedByPlayerId: null,
    objective: {
      displayName: "Give a crossing guard a hongbao",
      id: 18,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 2,
    cellY: 2,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 3,
    claimedByPlayerId: null,
    objective: {
      displayName: "Visit 8 temples",
      id: 3,
      countable: true,
      countLimit: 8,
    },
  },
  {
    cellX: 2,
    cellY: 4,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 21,
    claimedByPlayerId: null,
    objective: {
      displayName: "Visit the remaining city gates",
      id: 21,
      countable: true,
      countLimit: 4,
    },
  },
  {
    cellX: 3,
    cellY: 0,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 2,
    claimedByPlayerId: null,
    objective: {
      displayName: "Find a Simple Mart",
      id: 2,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 3,
    cellY: 1,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 6,
    claimedByPlayerId: null,
    objective: {
      displayName: "Ghostride a Youbike between two Youbike stations",
      id: 6,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 3,
    cellY: 3,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 1,
    claimedByPlayerId: null,
    objective: {
      displayName: "Cross a bridge",
      id: 1,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 4,
    cellY: 0,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 25,
    claimedByPlayerId: null,
    objective: {
      displayName: "Find 3 different district manhole covers ",
      id: 25,
      countable: true,
      countLimit: 3,
    },
  },
  {
    cellX: 4,
    cellY: 1,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 20,
    claimedByPlayerId: null,
    objective: {
      displayName: "Visit the CKS changing of the guard",
      id: 20,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 4,
    cellY: 2,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 5,
    claimedByPlayerId: null,
    objective: {
      displayName: "Buy anything from a 7x11",
      id: 5,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 4,
    cellY: 4,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 19,
    claimedByPlayerId: null,
    objective: {
      displayName: "Find an artistic representation of a magpie",
      id: 19,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 0,
    cellY: 2,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 14,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Visit an establishment owned by a friend",
      id: 14,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 0,
    cellY: 3,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 13,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Smash a stinky tofu",
      id: 13,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 1,
    cellY: 1,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 22,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Find an Indian Laurel Banyan tree",
      id: 22,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 0,
    cellY: 1,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 23,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Visit 2 district sports centers",
      id: 23,
      countable: true,
      countLimit: 2,
    },
  },
  {
    cellX: 1,
    cellY: 0,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 26,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Find a dog in a pram",
      id: 26,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 1,
    cellY: 2,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 15,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Find a Yonghe Doujiang shop",
      id: 15,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 1,
    cellY: 3,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 4,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Find a Simple Mart",
      id: 4,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 0,
    cellY: 4,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 16,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Find Falungong",
      id: 16,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 2,
    cellY: 3,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 7,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Find a binglang shop without binglang in the name",
      id: 7,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 3,
    cellY: 2,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 9,
    claimedByPlayerId: 1,
    objective: {
      displayName: "Bike through a tunnel",
      id: 9,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 3,
    cellY: 4,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 12,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Find a dog wearing clothes",
      id: 12,
      countable: false,
      countLimit: null,
    },
  },
  {
    cellX: 4,
    cellY: 3,
    claimedRealTime: null,
    boardId: "b0d7d4ec-8b76-4e2b-819e-081191570046",
    objectiveId: 10,
    claimedByPlayerId: 3,
    objective: {
      displayName: "Pound a bitter gourd smoothie",
      id: 10,
      countable: false,
      countLimit: null,
    },
  },
];
