import { Prisma } from "@prisma/client";

export const objectives: Prisma.ObjectiveCreateManyInput[] = [
  {
    countable: false,
    countLimit: null,
    displayName: "Cross a bridge",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a Simple Mart",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 8,
    displayName: "Visit 8 temples",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Buy anything from a 7X11",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Ghostride a Youbike between two Youbike stations",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a binglang shop without binglang (檳榔) in the name",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Bike (or walk your bike) through a night market",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Bike through a tunnel",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Pound a bitter gourd smoothie",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Visit a dog run",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a dog wearing clothes",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Smash a stinky tofu",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Visit an establishment owned by a friend",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a Yonghe Doujiang shop",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find Falungong",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a black FMD",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Give a crossing guard a hongbao",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find an artistic representation of a magpie",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Visit the CKS changing of the guard",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 4,
    displayName: "Visit the remaining city gates",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find an Indian Laurel Banyan tree",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 2,
    displayName: "Visit 2 district sports centers",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 10,
    displayName: "Find 10 beautiful dogs ",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: false,
    countLimit: null,
    displayName: "Find a mosaic mural",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 3,
    displayName: "Find a 20, 30, a 40 km/hour street sign",
    description: null,
    districtId: null,
    creatorId: 0,
  },
  {
    countable: true,
    countLimit: 2,
    displayName: "Find 2 panda bears, one 2D and one 3D",
    description: null,
    districtId: null,
    creatorId: 0,
  },
];
